### ISSUE TITLE
USB 2.0 HUB - PCBWay

### ISSUE THREAD

**Issue by jboxberger** [H1M4W4R1/H1M4W4R1#1]
Hi,

i found your Entry at https://forbot.pl/forum/topic/19681-hub-usb-20-w-wersji-diy/

Can you help me out designing a very small USB 2.0 HUB for PCBWay (not for free of course). I have already a real example but not the ability to design the PCB in the right format. Maybe you can modify your design to fit the Example on the picture and help me get the order wit PCBWay done?

Sorry for writing you here, haven't found any other contact information of you.

Kind Regards

![20230323_105342](https://user-images.githubusercontent.com/1545845/227167812-79e002e7-3b26-48ad-a0e4-9b7334220ba8.jpg)

**Comment by H1M4W4R1** [comment]
> Ar you sure with the mirrored data pins?

It depends on definition of "mirrored pins". Bottom image is always mirrored by default (eg. label text is reversed), that's why I use that definition for them.

Your image is mostly correct, did not check if power pins will match after mirroring the image... And they did not. I'll drop fixed version here:

[USB Hub Mini labelFix.zip](https://github.com/H1M4W4R1/H1M4W4R1/files/11054893/USB.Hub.Mini.labelFix.zip)

**Comment by jboxberger** [comment]
Thank you so much! Your'e Awesome. Do you have PayPal so i can appreciate your Help?

**Comment by H1M4W4R1** [comment]
> Thank you so much! Your'e Awesome. Do you have PayPal so i can appreciate your Help?

No problem. And no, I don't use PayPal (anymore) due to their stupid ideas. Use that "donation" to get some parts for yourself. That will be enough as "thank you" for me :)
